services:
  web:
    depends_on:
      restore:
        condition: service_completed_successfully
  web-2:
    depends_on:
      restore:
        condition: service_completed_successfully
  restore:
    build: 
      context: ./src
      dockerfile: ./restore.Dockerfile
    env_file:
      - restic_compose_backup.env
    volumes:
     ## Map local restic repository for dev
      - ./restic_data:/restic_data
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - restored_data:/restored_data
    depends_on:
      mariadb:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - default
      - global
networks:
  global:
    external: true
volumes:
  restored_data: ~