services:
  web:
    build: 
      context: ./src
      dockerfile: ./testapp.Dockerfile
    labels:
      restic-compose-backup.volumes: true
      restic-compose-backup.volumes.include: "/tests"
    volumes:
      - ./live_two_filestores/src/tests:/srv/tests
      - ./live_two_filestores/.vscode:/srv/code
    environment:
      - SOME_VALUE=test
      - ANOTHER_VALUE=1
    networks:
      - default
      - global

  web-2:
    build: 
      context: ./src
      dockerfile: ./testapp.Dockerfile
    labels:
      restic-compose-backup.volumes: true
      restic-compose-backup.volumes.exclude: "/tests"
    volumes:
      - ./live_two_filestores/src/tests:/srv/tests
      - ./live_two_filestores/.vscode:/srv/code
    environment:
      - SOME_VALUE=test
      - ANOTHER_VALUE=1
    networks:
      - default
      - global

  mariadb:
    image: mariadb:10
    labels:
      restic-compose-backup.mariadb: true
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_DATABASE=mydb-mariadb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - mariadbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - default
      - global

  postgres:
    image: postgres:13
    labels:
      restic-compose-backup.postgres: true
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
      - POSTGRES_DB=test-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    networks:
      - default
      - global

volumes:
  mariadbdata:
  pgdata:

networks:
  global:
    external: true
